services:
  kn-bigwork:
    image: neo4j:latest
    container_name: kn-bigwork
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7477:7474"
      - "7688:7687"
    volumes:
      - ./assets/neo4j-data:/data
